In [99]:
import numpy as np
p = 5
n = 1
q = p^n
F = FiniteField(q,'a')
a = F.gen()

if n > 1:
    Set = range(1,q)
    Set = [a^j for j in Set]
    Set = [0] + Set
else: 
    Set = range(1,q)
    Set = [(a+a+a)^j for j in Set]
    Set = [0] + Set
print vector(Set)
#G = SymmetricGroup([Set[1],Set[2],Set[0],Set[3]])
G = SymmetricGroup(Set)

(0, 3, 4, 2, 1)


In [100]:
def Matrica(F,p,n,Set):
    M = matrix(F, q, q)
    
    M[0,0] = -1

    for i in range(1,q-1):
        k = q-(i+1)
        for j in range(1,q):
            M[i,j] = (Set[j])^(k)

    for i in range(q):
        M[q-1,i] = 1
    
    M = -M
    
    return M

print Set
M = Matrica(F,p,n,Set)
print M 

[0, 3, 4, 2, 1]
[1 0 0 0 0]
[0 3 1 2 4]
[0 1 4 1 4]
[0 2 1 3 4]
[4 4 4 4 4]


In [101]:
def orbit_of(vctr):
    orbit = []
    for g in G:
        tmp = []
        for item in vctr:
            tmp.append( g.dict()[item] )
        orbit.append(tmp)
    return orbit
        
def orbit_first_type(vctr):
    orbit = []
    for g in G:
        tmp = []
        for item in vctr:
            tmp.append( g.dict()[item] )
        orbit.append( g.inverse()(tmp) )
    return orbit

def remove_repetitions(lst):
    tmp = []
    for i in lst:
        if i not in tmp:
            tmp.append(i)
    return tmp

def number_of_different_values(lst):
    return len( set(lst) )


def get_vector(m, qq=q, lst=Set):
    if m>=qq**qq: 
        raise Exception('your argument of function is ' 
                        + str(m) 
                        +' but it must be less then '
                        + str(qq**qq))
    tmp = []
    while m!=0:
        remr = m%qq
        m = (m-remr)/qq
        tmp.insert(0,lst[remr])
        
    for i in xrange(qq-len(tmp)):
        tmp.insert(0,lst[0])
    return tmp


def nz_pol(pol):
    i=0
    for c in pol:
        if c!=0:
            i+=1
    return i

def key_nz(lst):
        return lst[0]
    
def key_nz_class(lst):
        return lst[0][0]

In [102]:
classes1 = []
in_classes1 = []
vctr1 = []
orbit1 = []
d = q^q
c = 0
for i in xrange(q^q):
    c = 0
    vctr1 = get_vector(i)
    for k in xrange(len(in_classes1)):
        if vctr1 == in_classes1[k]:
            c = 1
            break
    if c == 1:
        continue
    else:
        orbit1 = remove_repetitions(orbit_first_type(vctr1)) 
        for j in xrange(len(orbit1)):
            in_classes1.append(orbit1[j])
        classes1.append(orbit1)
        
        
        if len(in_classes1) == d:
            break
            
for cls in classes1:
    for i in xrange(len(cls)):
        pol = list(M*vector(cls[i]))
        cls[i] = [nz_pol(pol), cls[i], list(M*vector(cls[i]))]
        
for cls in classes1:
    cls.sort(key = key_nz)
classes1.sort(key = key_nz_class, reverse = True)

In [103]:
#первый тип
#генерит летех графы в файл, который надо 
#скопировать и вставить в окружение [document]
f = open('graph_prilozhenie.txt', 'w')

out = r'''\
\section*{{Классы первого типа для $P_{0}$. $L^{{\Rmnum{{1}}}}({0}) = {2}.$}}
\fancyhead[L]{{$q={0}, \quad \text{{ набор аргументов }} {1}$}}
'''.format(q, latex(vector(Set)), classes1[0][0][0])
f.write(out)

for cls in classes1:
    num = cls[0][0]
    tmp = cls[0][1]
    out = 'Для функций из приведенного ниже класса достигается значение $l(f) = {}.$\n\n'.format(num)
    out = out + r'''\
Граф класса:
\begin{table}[H]
\begin{tikzpicture}[
auto,
place/.style={
circle,
draw=black!100,
inner sep=0pt,
minimum size=3mm
},>=stealth,thick
]
'''
    l=len(tmp)
    phi = 360/l
    
    for i in xrange(l):
        out = out + r'\node[place] (v{0}) at ({1}:1.5)'.format(i,i*phi)+'{};\n'    
    
    for i in xrange(l):
        if Set[i] == tmp[i]:
            angle = i*phi
            out = out + \
'\\draw [->] (v{0}) to [out={1},in={2},looseness=15] (v{0});\n'.format(i, angle + 30, angle-30)

        else:
            ind = Set.index(tmp[i])
            out = out + '\\draw [->] (v{0}) to (v{1});\n'.format(i, ind)
    out = out + r'''\end{tikzpicture}
\end{table}

Функции из класса и их полиномы:
'''
    f.write(out)
    f.write('\\begin{{alignat*}}{{ {} }}\n'.format(len(cls)+1))
    for i in xrange(len(cls)):
        func = vector(cls[i][1])
        poly = vector(cls[i][2])
        out = '\
v_{y_{' + str(i) + '}}(x) &=' + latex(func) + '\\qquad & \
v_{p_{y_{' + str(i) + '}}}(x) &=' + latex(poly) + r'\\' + '\n'
        f.write(out)
        
    f.write(r'''\
& & &
\end{alignat*}
\hfill $\blacksquare$
\newpage


''')
    if q==7:
        if cls[0][0] < q-2:
            break
f.close() 

In [228]:
#второй тип
classes = []
in_classes = []
vctr = []
orbit = []
c = 0
d = q^q
for i in xrange(0,q^q):
    c = 0
    vctr = get_vector(i)
    for k in xrange(len(in_classes)):
        if vctr == in_classes[k]:
            
            c = 1
            break
    if c == 1:
        continue 
    else:
        orbit = remove_repetitions(orbit_of(vctr)) 
        for j in xrange(len(orbit)):
            in_classes.append(orbit[j])
        classes.append(orbit)
        
        if len(in_classes) == d:
            break
    
for cls in classes:
    for i in xrange(len(cls)):
        pol = list(M*vector(cls[i]))
        cls[i] = [nz_pol(pol), cls[i], list(M*vector(cls[i]))]
        
for cls in classes:
    cls.sort(key = key_nz)
classes.sort(key = key_nz_class, reverse = True)

In [232]:
#второй тип
f = open('graph_type2.txt', 'w')

out = r'''\
\section*{{Классы второго типа для $P_{0}$. $L({0}) = {2}.$}}
\fancyhead[L]{{$q={0}, \quad \text{{ набор аргументов }} {1}$}}
'''.format(q, latex(vector(Set)), classes[0][0][0])
f.write(out)

for cls in classes:
    num = cls[0][0]
    out = 'На нижеследующем классе достигается значение $l(f) = {}$\n\n'.format(num)
    f.write(out)

    for i in xrange(len(cls)):
        func = vector(cls[i][1])
        poly = vector(cls[i][2])
        out = '\
$$v_{y_{' + str(i) + '}}(x) =' + latex(func) + '\\qquad \
v_{p_{y_{' + str(i) + '}}}(x) =' + latex(poly) + '$$\n\n'
        f.write(out)
        
        tmp = list(func)
        out = r'''\
\begin{table}[H]
\begin{tikzpicture}[
auto,
place/.style={
circle,
draw=black!100,
inner sep=0pt,
minimum size=3mm
},>=stealth,thick
]
'''
        l=len(tmp)
        phi = 360/l
    
        for i in xrange(l):
            out = out + r'\node[place] (v{0}) at ({1}:1.5)'.format(i,i*phi)+'{};\n'    
    
        for i in xrange(l):
            if Set[i] == tmp[i]:
                angle = i*phi
                out = out + \
'\\draw [->] (v{0}) to [out={1},in={2},looseness=15] (v{0});\n'.format(i, angle + 30, angle-30)

            else:
                ind = Set.index(tmp[i])
                out = out + '\\draw [->] (v{0}) to (v{1});\n'.format(i, ind)
        out = out + r'''\end{tikzpicture}
\end{table}

'''
        f.write(out)
        
    f.write(r'''\
\hfill $\blacksquare$
\newpage


''')
    break
f.close()

In [233]:
len(classes[0])

20

In [ ]:
#для 7
#первый тип
#генерит летех графы в файл, который надо 
#скопировать и вставить в окружение [document]
f = open('graph_prilozhenie.txt', 'w')

out = r'''\
\section*{{Классы первого типа для $P_{0}$. $L({0}) = {2}.$}}
\fancyhead[L]{{$q={0}, \quad \text{{ набор аргументов }} {1}$}}
'''.format(q, latex(vector(Set)), classes1[0][0][0])
f.write(out)

for cls in classes1:
    num = cls[0][0]
    tmp = cls[0][1]
    out = 'Для функций из приведенного ниже класса достигается значение $l(f) = {}.$\n\n'.format(num)
    out = out + r'''\
Граф класса:
\begin{table}[H]
\begin{tikzpicture}[
auto,
place/.style={
circle,
draw=black!100,
inner sep=0pt,
minimum size=3mm
},>=stealth,thick
]
'''
    l=len(tmp)
    phi = 360/l
    
    for i in xrange(l):
        out = out + r'\node[place] (v{0}) at ({1}:1.5)'.format(i,i*phi)+'{};\n'    
    
    for i in xrange(l):
        if Set[i] == tmp[i]:
            angle = i*phi
            out = out + \
'\\draw [->] (v{0}) to [out={1},in={2},looseness=15] (v{0});\n'.format(i, angle + 30, angle-30)

        else:
            ind = Set.index(tmp[i])
            out = out + '\\draw [->] (v{0}) to (v{1});\n'.format(i, ind)
    out = out + r'''\end{tikzpicture}
\end{table}

Функции из класса и их полиномы:
'''
    f.write(out)

    for i in xrange(len(cls)):
        func = vector(cls[i][1])
        poly = vector(cls[i][2])
        out = '\
$$v_{y_{' + str(i) + '}}(x) =' + latex(func) + '\\qquad \
v_{p_{y_{' + str(i) + '}}}(x) =' + latex(poly) + '$$ \n'
        f.write(out)
        
    f.write(r'''\
\hfill $\blacksquare$
\newpage


''')
    if q==7:
        if cls[0][0] < q-2:
            break
f.close() 